name: PHP Matrix
description: TODO

author: Typist Tech Limited
branding:
  icon: grid
  color: black

inputs:
  mode:
    description: Version format
    default: minor-only

  source:
    description: Source of releases information
    default: auto

outputs:
  matrix:
    description: The PHP version matrix

runs:
  using: docker
  image: Dockerfile
