# Taken from https://github.com/typisttech/.github/blob/8c3b859e35165a6e81a660713be195ec61d2ca1d/.github/workflows/lint-actions.yml
name: Lint GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .github/workflows
          sparse-checkout-cone-mode: false

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
