name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/publish-immutable-action@v0.0.4
        with:
          github-token: ${{ github.token }}
